### ISSUE TITLE
Evil Dead - Hail to the King (Europe) (Disc 1) has flickering textures with Vulkan and D3D11 at native resolution

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1430]
I'm sure it's not specific to the Euro version, that's just the one I was using. It happens with Vulkan and D3D11 at native resolution but not when upscaling. It doesn't happen with OpenGL or Software at all. Start the game and look at the right side of the box with the gas can and the bottom of the box with the converter. 

![Capture](https://user-images.githubusercontent.com/77198254/104117299-4d1d2700-5374-11eb-81e1-cc2e6e697b9a.PNG)

**Comment by stenzek** [comment]
Seems specific to NVIDIA, should be fixed with https://github.com/stenzek/duckstation/commit/97971464d19d1f86b7e7e0da7224ed80dd8ad275

**Comment by Kurayami7** [comment]
The flickering is less obvious and has changed position but is still happening. It now happens in the middle of the box. 

![Capture](https://user-images.githubusercontent.com/77198254/104150721-e446b500-542e-11eb-8f0e-86af7714b03a.PNG)

**Comment by stenzek** [comment]
Not seeing any flickering here on a GTX1080, nor with the WARP driver. Might just be within the error tolerance of PC GPUs.

**Comment by Kurayami7** [comment]
The game seems to have regressed. This now happens when you skip the opening cutscene at native resolution. 

![Capture2](https://user-images.githubusercontent.com/77198254/104151237-9763de00-5430-11eb-84d1-9117dbdcd786.PNG)

**Comment by stenzek** [comment]
No issues here at native resolution with D3D11/Vulkan/Software:

![image](https://user-images.githubusercontent.com/11288319/104152139-71d3d600-542a-11eb-8a86-c992b39797cd.png)

**Comment by Kurayami7** [comment]
Dunno then. Do you want me to close this?
