### ISSUE TITLE
Part of Lara's dialogue gets cut off in the training level in Tomb Raider (USA) (Rev 3)

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1589]
When she says "Welcome to my home" there's a few seconds of audio silence which results in the W in "Welcome" getting cut off. Tested with all enhancements off and with the software renderer. Tested on real hardware and doesn't happen.

[SLUS-00152_2021-02-06_20-11-06.zip](https://github.com/stenzek/duckstation/files/5937175/SLUS-00152_2021-02-06_20-11-06.zip)

![SLUS-00152_2021-02-07_03-12-22](https://user-images.githubusercontent.com/77198254/107123695-0c70e900-68f3-11eb-93af-28f90e72de8e.png)

**Comment by stenzek** [comment]
Needs further research - something to do with the game increasing the volume too late, based on CDDA reports?

**Comment by Richard-L** [comment]
Interesting, I thought this was normal.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/56c08254c9a5c3c84d3eb7fae33bcd47c90e7ecd

**Comment by waspennator** [comment]
Tested this out again with the latest preview build and can confirm the "Welcome to my home" line still gets cut off a bit at the beginning

**Comment by stenzek** [comment]
Are you certain this is not the intended behavior? TR constantly polls the CD-ROM for its position and unmutes the audio as soon as it sees 00:00:00 on the track (outside of the pregap). DuckStation was off by one CD frame previously here, but as best I can tell it's working as intended now.

**Comment by waspennator** [comment]
Mostly just tryin to double check on hardware and other vids on youtube, some of em have the welcome play out fully, other's just have the w cut out slightly.

**Comment by foxsevent** [comment]
Can't say for og hardware but said "cut" is present on PS3 and PSP/Vita so I'd say it works as intended.

I think the issue here is here that it takes a solid second for the audio clip to start playing so it sounds as if it's cut, where as on the PC version of TR1 that audio clip starts as soon as the level loads.

**Comment by Richard-L** [comment]
This is a nice little improvement. I think it plays the track perfectly. Some of TR1's audio track beginnings and ends are pretty sharp.
