### ISSUE TITLE
Legend of Legaia (USA) hangs partway through the Conkram mirror cutscene

### ISSUE THREAD

**Issue by Kurayami7** [stenzek/duckstation#1645]
Tested with all enhancements off. Tested with a redump verified copy of the game. Tested with both interpreter and recompiler. 

[Legend of Legaia (USA)_1.zip](https://github.com/stenzek/duckstation/files/5984689/Legend.of.Legaia.USA._1.zip)

Enter the castle and go up these stairs. 

![SCUS-94254_2021-02-16_10-41-08](https://user-images.githubusercontent.com/77198254/108002707-8b2cfb00-7044-11eb-81de-0a1bc44d76cd.png)

Go through this door on the right.

![SCUS-94254_2021-02-16_10-42-49](https://user-images.githubusercontent.com/77198254/108002721-97b15380-7044-11eb-888c-6f7a0b9a827b.png)

After you enter the mirror the game will hang and loop the same audio over and over.

![SCUS-94254_2021-02-16_10-29-08](https://user-images.githubusercontent.com/77198254/108002775-c0394d80-7044-11eb-925c-1c924290c53f.png)

![Capture](https://user-images.githubusercontent.com/77198254/108002818-e0690c80-7044-11eb-9b10-c593bdfb2925.PNG)

**Comment by foxsevent** [comment]
One small detail missed is to load up save file nr 2 Conkram.
in my case the game freezes during the fade out on that scene and occasionally fives me an in game error message.
Same deal No enhancements and interpreter.
![SCUS-94254_2021-02-16_01-21-29](https://user-images.githubusercontent.com/64225743/108004365-f3a0bb80-6ff5-11eb-9077-11af2a28c2f8.png)

**Comment by stenzek** [comment]
Seems to be timing related - I couldn't crash it all with a 10% underclock.

**Comment by nicolasnoble** [comment]
FWIW, I managed to reproduce it on pcsx-redux by overclocking the CPU :-)

Code of the game is horrendous.

**Comment by stenzek** [comment]
Fixed in https://github.com/stenzek/duckstation/commit/fdc7066ead2196886516c8845af870334722f00d (or, at least I can't reproduce it anymore).

**Comment by Kurayami7** [comment]
This isn't fixed. with all settings default + + software renderer + recompiler + very latest version it's still hanging in the exact same spot every time. 

![Capture](https://user-images.githubusercontent.com/77198254/110371510-2f80eb00-80a1-11eb-90f4-38d6efe3af2c.PNG)

**Comment by stenzek** [comment]
Yes, you need icache on. But it should be turned on by compatibility settings automatically unless you have disabled "apply game settings".

**Comment by Kurayami7** [comment]
Uh, I dunno. Completely fresh duck download, no settings touched. 

![Capture](https://user-images.githubusercontent.com/77198254/110402084-db8cfb00-80ce-11eb-8e91-43b0c92eb559.PNG)

**Comment by stenzek** [comment]
Turns out I had a typo in the serial for the US version. Will push a fix later.

Game settings are applying and opening/editing fine here.
