### ISSUE TITLE
Bit of dialogue missing in Spider-man [SLUS-00875]

### ISSUE THREAD

**Issue by Phantasm90** [stenzek/duckstation#1845]
**Game details**
[SLUS-00875 Spider-man (USA)]

**Description of the issue / bug**
After you find the lizard in the level "The Lizard's Maze" and he's done explaining how to get to Mary Jane, Spider-man is supposed to say "Thanks lizard", yet the emulator doesn't play that bit of audio, while mednafen plays it fine

[https://youtu.be/zFAx2KIiByw?t=77](https://youtu.be/zFAx2KIiByw?t=77)

[Spider-man (Duckstation & Mednafen).zip](https://github.com/stenzek/duckstation/files/6174910/Spider-man.Duckstation.Mednafen.zip)

**Enhancements information**
No enhancements, default settings

**Hardware/software**
Windows 7 Ultimate
HP Pavillion dv4 intel i5 2,27GH
D3D11

**Emulator version**
0.1-3600-g1e1d864e (dev)

**Comment by stenzek** [comment]
Please re-test on the preview build, another similar issue was already fixed there.

**Comment by Phantasm90** [comment]
Just tested it on the preview build and it still doesn't  play that bit of dialogue

**Comment by Phantasm90** [comment]
Ok i just tested it with Force Recompiler Icache and it plays the dialogue now, it also seems to have fixed the [#1571](https://github.com/stenzek/duckstation/issues/1571) swing bug for me

**Comment by stenzek** [comment]
Interesting. Thanks for checking, I'll add a compatibility override for this tomorrow.

**Comment by Phantasm90** [comment]
Out of curiosity i wanted to see if this bug happens on other versions and indeed it does in the european one [SLES-02886], except it also misses the "where is she?" from Spidey, i tried to fix it with icache it didn't help, same with interpreter

[Spider-man - lizard (europe).zip](https://github.com/stenzek/duckstation/files/6176592/Spider-man.-.lizard.europe.zip)

You can test it by going into the special menu and typing the cheat EEL NATS to select the level, the youtube video i posted show how to get to the lizard

Oddly enough, the japanese version seems to be fine with or without icache, i'll check out later the other versions

**Comment by Phantasm90** [comment]
Just tested with the latest build and the Europe (SLES-02886), Spain (SLES-02890) and Italy (SLES-02889) versions all have the same problem with or without Force Recompiler Icache, it only happens with the english voices since the dubbed versions (japanese, french and german) seem to be fine

**Comment by stenzek** [comment]
Added the compatibility override for icache, we'll track the other issues in #1571 rather than having two threads.
