### ISSUE TITLE
Captain Commando (Japan) // Corruption on first boss sprite.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#356]
The first boss sprite is corrupted.

A flickering band is present on the right side during the gameplay.

![CapCom](https://user-images.githubusercontent.com/52127625/80425282-a5de8980-88e3-11ea-900e-3c5649bdfb61.jpg)

Note - This game is known to be complex to emulate correctly.
First stage's boss' graphics are all kinds of corrupt if CD sector buffering is incorrect (particularly in relation of GetLocL vs GetLocP vs. raw sector data time fields).

**Comment by stenzek** [comment]
The stuff on the right is probably a cropping issue.

The sprite stuff may not be related to the CD-ROM Controller, GetLocL/GetLocP should behave correctly, at least they were when I compared them to my hardware/console tests from a little while back.

**Comment by Zet-sensei** [comment]
The flickering band is fixed since https://github.com/stenzek/duckstation/commit/d6f61543806907c7076336e68ec3b679b2e6071f

The boss sprite remains corrupted.

**Comment by kurayami6** [comment]
Still an issue as of the latest version. 

![SLPS-01567_2020-06-04_11-22-28](https://user-images.githubusercontent.com/31968468/83704719-44ce7200-a656-11ea-9435-0beb054cd8eb.png)

**Comment by Shideravan** [comment]
I can confirm that this happens in software renderer and in the interpreter mode too. Tested in 0.1-1409-ge198e315.

**Comment by rafaelmartines** [comment]
The actual version has the problem with thet first boss and some of the mobs in the third stage.
![image](https://user-images.githubusercontent.com/8183691/106951721-e38ffe80-670e-11eb-9565-0db06a6afa03.png)

![image](https://user-images.githubusercontent.com/8183691/106951671-d07d2e80-670e-11eb-90af-49fe0e58ae88.png)
