### ISSUE TITLE
Water in Soul Blade (USA) (v1.1) is broken with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#371]
It's broken when upscaling D3D11 and at all resolutions with OpenGL.

OpenGL and D3D11 at x4

![SLUS-00240_2020-04-29_13-49-12](https://user-images.githubusercontent.com/31968468/80559506-0c1cf680-8a21-11ea-923d-aa22373dc305.png)

OpenGL at native resolution.

![Capture](https://user-images.githubusercontent.com/31968468/80559523-1939e580-8a21-11ea-8569-5906d11c5a60.PNG)

**Comment by stenzek** [comment]
Looks like the same issue as Doom, Dark Forces, etc.

I'll probably have to add a CPU-side check to expand these triangles, because for those Doom, it's easier to just lock it to 1x because it won't benefit from upscaling, but it looks like this game has at least some 3D so it will.

**Comment by stenzek** [comment]
I believe this is fixed on OpenGL now. It remains an upscaling issue.

**Comment by Shideravan** [comment]
The error still happens in Li Long stage water in Vulkan, in 0.1-1409-ge198e315

**Comment by andercard0** [comment]
Indeed still happening  as you may view  here as reported by "Deus'' on discord he has a Japanese version juste tested here as well

![image](https://user-images.githubusercontent.com/43047877/107883273-c3a9c900-6ecc-11eb-9e3f-fee2194f63b9.png)

**Comment by ToniBC** [comment]
The water error is still present, but the issue was closed. It was partially repaired, but it is still there and can be solved because others do.
