### ISSUE TITLE
UEFA Champions League - Season 1999-2000 (Europe) crashes before a match

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#476]
![crash](https://user-images.githubusercontent.com/31968468/82737123-e1009b00-9d71-11ea-8e4a-6ccb1c15b5a5.PNG)

![crash2](https://user-images.githubusercontent.com/31968468/82737124-e5c54f00-9d71-11ea-82e7-c800c230d26b.PNG)

**Comment by stenzek** [comment]
Same issue as https://github.com/stenzek/duckstation/issues/219.

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/4e8da3cb417ad54d211327cfe0cde450bead45d4

Given the game doesn't actually use the sound map feature (it just enables then immediately disables it), I wouldn't have been able to test the implementation anyway. So, the search for something which actually uses it and we can test with continues. If such a game does exist, you should see an error about both sound map and buffer writes in the log.

**Comment by kurayami6** [comment]
It still crashes, just now with this in the log instead of an error popup.

![Capture](https://user-images.githubusercontent.com/31968468/83053584-487d5a00-a094-11ea-8722-167606efdd13.PNG)

**Comment by Zet-sensei** [comment]
The game loads fine on my end.
Tested on 0.1-1998-g43bafe1a.

Issue should be closed.

![UEFA](https://user-images.githubusercontent.com/52127625/95695744-b63bb400-0c38-11eb-952c-1ddeb0306002.jpg)
